export default function TermsPage() {
  return (
    <div className="max-w-[640px] mx-auto px-6 py-12">
      <h1 className="font-brand text-3xl font-normal tracking-[-0.3px] mb-6">Terms of Use</h1>
      <p className="text-xs text-gray-400 mb-8">Last updated: April 2026</p>

      <div className="space-y-6 text-sm text-gray-600 leading-relaxed">
        <section>
          <h2 className="text-[15px] font-medium text-foreground mb-2">Service Description</h2>
          <p>First Pass Coverage provides AI-generated screenplay analysis. The service produces coverage reports including loglines, synopses, rated evaluations, and recommendations based on uploaded screenplay PDFs.</p>
        </section>

        <section>
          <h2 className="text-[15px] font-medium text-foreground mb-2">Your Content</h2>
          <p>You retain all rights to any screenplay or material you upload. Uploaded files are processed in real time to generate coverage and are not stored after processing is complete. We do not claim any ownership or license over your uploaded material.</p>
        </section>

        <section>
          <h2 className="text-[15px] font-medium text-foreground mb-2">Coverage Output</h2>
          <p>Coverage reports generated by the service are provided for informational purposes. They represent an automated analysis and should not be considered a substitute for professional human judgment. Ratings and recommendations reflect the output of the evaluation framework at the time of generation and often vary between analyses of the same material.</p>
        </section>

        <section>
          <h2 className="text-[15px] font-medium text-foreground mb-2">Acceptable Use</h2>
          <p>You agree to use the service only with material you have the right to upload and analyze. You may not use the service to process material you do not own or have authorization to evaluate.</p>
        </section>

        <section>
          <h2 className="text-[15px] font-medium text-foreground mb-2">Limitation of Liability</h2>
          <p>First Pass Coverage is provided &ldquo;as is&rdquo; without warranties of any kind. We disclaim any liability for decisions made based on coverage output, nor for any damages arising from use of the service.</p>
        </section>

        <section>
          <h2 className="text-[15px] font-medium text-foreground mb-2">Changes to Terms</h2>
          <p>We reserve the right to update these terms as the service evolves. Continued use of the service after changes constitutes acceptance of the updated terms.</p>
        </section>

        <section>
          <h2 className="text-[15px] font-medium text-foreground mb-2">Contact</h2>
          <p>Questions about these terms: <a href="mailto:contact@firstpasscoverage.com" className="text-foreground underline underline-offset-2 hover:opacity-70 transition-opacity">contact@firstpasscoverage.com</a></p>
        </section>
      </div>
    </div>
  );
}
